### ISSUE TITLE
Parameters missing various fields

### ISSUE THREAD

**Issue by alexec** [bootprint/bootprint-openapi#88] opened 2017-02-02 17:22 UTC
When a parameter is rendered in a table, it has the data type, and whether or not it is required. But, it is missing `pattern` and `format` fields.

**Comment by nknapp** [comment] 2017-02-13 21:31
Would be great if you had a short example that I could use as test-case. This might be fixed with bootprint/bootprint-json-schema#10 (at least for patterns)

**Comment by NelsonTriesCoding** [comment] 2017-05-19 12:47
I'm not sure if this is related, I may make a new issue if you think this should be one.

So, my parameters aren't showing in the table. 

Sample : 

``` 
/**
 * @swagger
 * /login:
 *   post:
 *    description: Authenticate user.
 *    produces:
 *      - application/json
 *    parameters:
 *      - name: email
 *        in: body
 *        required: true
 *        type: string
 *      - name: password
 *        in: body
 *        required: true
 *        type: string
 *    responses:
 *      '200':
 *        type: object
 *        properties:
 *          JSESSIONID:
 *              type: String
 *          required:
 *            - JSESSIONID
 */
```

So this renders a table in the HTML file with the method (post) the title (/login) and the response (200) but the parameter field is empty. Also the properties of '200' don't show up. 

What I'm running in the console is :  `swagger-jsdoc-generator swagspec.json > config.json && bootprint openapi config.json swagger` where "swagspec" is my configuration file, config.json is the json generated from the swagger comments (I should rename it, I now this might be confusing) and swagger is the folder where the HTML and CSS are saved.

Any idea on what's the problem is?

**Comment by nknapp** [comment] 2017-05-19 15:25
This is a separate issue. There should be a `schema`-property in the response-object

**Closed** 2019-02-11 22:01 UTC
